### ISSUE TITLE
Note about DetrendPC/PC change between v1.5.0 and v1.6.0

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/fcp-indi.github.com#202]
v1.5.0 `method:PC` for aCompCor is the same as running `method:DetrendPC`:

```
  aCompCor:
    extraction_resolution: 2
    summary:
      components: 5
      method: PC
    tissues:
    - WhiteMatter
    - CerebrospinalFluid
```

However, v1.6.0+ `method:PC` and `method:DetrendPC` are different!
